version: '3'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # автоинициализация
  app:
    build: .
    depends_on:
      - db